<?php
/**
 * Copyright © NeutromeLabs. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace NeutromeLabs\Mcp\Api;

use Exception;

/**
 * Interface CodeExecutionServiceInterface
 * Provides methods for executing code and commands via MCP.
 * @api
 * @since 1.1.0 // Assuming a version bump for new features/refactoring
 */
interface CodeExecutionServiceInterface
{
    /**
     * Execute arbitrary PHP code.
     * Requires explicit user approval via MCP client.
     *
     * @param string $code The PHP code to execute.
     * @return string The output generated by the executed code (e.g., from echo, print) or an error message.
     * @throws Exception If execution fails.
     */
    public function executePhp(string $code): string;

    /**
     * Execute an arbitrary SQL query.
     * Requires explicit user approval via MCP client.
     *
     * @param string $query The SQL query to execute.
     * @return string A summary of the result (e.g., "OK", "X rows affected", "Y rows returned") or an error message.
     * @throws Exception If execution fails.
     */
    public function executeSql(string $query): string;

    /**
     * Execute an arbitrary shell command.
     * Requires explicit user approval via MCP client.
     * WARNING: Extremely dangerous. Allows arbitrary command execution on the server.
     *
     * @param string $command The shell command to execute.
     * @return string The output from the command or an error message.
     * @throws Exception If execution fails.
     */
    public function executeShell(string $command): string;
}
