<?php
/**
 * Copyright © NeutromeLabs. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace NeutromeLabs\Mcp\Api;

/**
 * Interface for executing code and queries via MCP.
 * @api
 */
interface ExecutionInterface
{
    /**
     * Execute arbitrary PHP code.
     * Requires explicit user approval via MCP client.
     *
     * @param string $code The PHP code to execute.
     * @return string The output generated by the executed code (e.g., from echo, print) or an error message.
     * @throws \Exception If execution fails.
     */
    public function executePhp(string $code): string;

    /**
     * Execute an arbitrary SQL query.
     * Requires explicit user approval via MCP client.
     *
     * @param string $query The SQL query to execute.
     * @return string A summary of the result (e.g., "OK", "X rows affected", "Y rows returned") or an error message.
     * @throws \Exception If execution fails.
     */
    public function executeSql(string $query): string;

    /**
     * Execute an arbitrary shell command.
     * Requires explicit user approval via MCP client.
     * WARNING: Extremely dangerous. Allows arbitrary command execution on the server.
     *
     * @param string $command The shell command to execute.
     * @return string The output from the command or an error message.
     * @throws \Exception If execution fails.
     */
    public function executeShell(string $command): string;

    /**
     * Get a list of all enabled Magento modules.
     *
     * @return string[] List of module names (e.g., ['Magento_Catalog', 'NeutromeLabs_Mcp']).
     * @throws \Exception If retrieval fails.
     */
    public function getModuleList(): array;

    /**
     * Get a list of files and directories within a specific module.
     *
     * @param string $moduleName The name of the module (e.g., 'NeutromeLabs_Mcp').
     * @return \NeutromeLabs\Mcp\Api\Data\ModuleFileNodeInterface[] A list of root nodes (files/directories) for the module.
     * @throws \Magento\Framework\Exception\LocalizedException If the module is not found.
     * @throws \Exception If retrieval fails.
     */
    public function getModuleFiles(string $moduleName): array; // Keep array hint for PHP, Magento DI handles conversion

    /**
     * Get the content of a specific file within a module.
     *
     * @param string $moduleName The name of the module (e.g., 'NeutromeLabs_Mcp').
     * @param string $filePath The relative path to the file within the module's directory (e.g., 'etc/module.xml').
     * @return string The content of the file or an error message.
     * @throws \Magento\Framework\Exception\LocalizedException If the module or file is not found or not readable.
     * @throws \Exception If retrieval fails.
     */
    public function getModuleFileContent(string $moduleName, string $filePath): string;
}
